In [68]:
import numpy as np

Arrays

In [69]:
# Zeros
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [70]:
# Ones
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [71]:
# Uniformed array v1
# np.zeros(15) + 20

# Uniformed array v2
np.ones(15) * 20

array([20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
       20., 20.])

In [72]:
# Incremental array
np.arange(1,100+1)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [73]:
 # Steps array
np.arange(10,1000+10,10)

array([  10,   20,   30,   40,   50,   60,   70,   80,   90,  100,  110,
        120,  130,  140,  150,  160,  170,  180,  190,  200,  210,  220,
        230,  240,  250,  260,  270,  280,  290,  300,  310,  320,  330,
        340,  350,  360,  370,  380,  390,  400,  410,  420,  430,  440,
        450,  460,  470,  480,  490,  500,  510,  520,  530,  540,  550,
        560,  570,  580,  590,  600,  610,  620,  630,  640,  650,  660,
        670,  680,  690,  700,  710,  720,  730,  740,  750,  760,  770,
        780,  790,  800,  810,  820,  830,  840,  850,  860,  870,  880,
        890,  900,  910,  920,  930,  940,  950,  960,  970,  980,  990,
       1000])

In [74]:
# Matrix
np.arange(10,250+10,10).reshape(5,5)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [75]:
# Identity matrix (diagonal)
np.eye(7)*20

array([[20.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 20.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 20.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 20.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 20.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 20.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 20.]])

In [76]:
# NumPy random function
np.random.rand(15)

array([0.9282438 , 0.48251588, 0.96836119, 0.90127367, 0.79504699,
       0.61419984, 0.55966788, 0.06349008, 0.67327559, 0.26153611,
       0.83590092, 0.58349725, 0.28912042, 0.36932888, 0.02136987])

In [77]:
# Random of normal distribution
np.random.randn(50).reshape(10,5)

array([[-1.05889335, -0.7409857 , -1.33676715, -0.64007253,  0.35722926],
       [-0.42868613, -0.61835659, -0.92083144, -0.16273799,  0.1668955 ],
       [-0.52398715, -1.07502158,  0.15394872, -0.27953726, -0.43828207],
       [ 2.04332997,  0.59935874, -0.35619422,  0.55840495, -0.33214321],
       [-0.12365524,  0.40322063, -0.02443822,  0.05657848,  0.73190336],
       [ 1.67367351,  0.35169402,  1.3358074 , -0.59675577,  0.77474511],
       [ 0.11038559,  1.01175716, -0.07149547,  1.49054349, -0.63115031],
       [ 0.72662963,  0.50190263, -0.76777428, -0.50196149, -1.61875401],
       [-0.73524914,  1.07584468,  1.15684808, -1.41061604,  1.04500408],
       [ 0.29569777,  0.86610211, -0.31795656, -0.04327412,  0.01812168]])

Exercise

In [78]:
# Create array with 0.01 steps

# Version 1 with actual decimal
# np.arange(.01,1+.01,.01).reshape(10,10)

# Version 2 with divisor at the end
np.arange(1,100+1).reshape(10,10)/10

array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ],
       [ 3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ],
       [ 4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

In [79]:
# Linear space (series divided evenly)
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [80]:
some_matrix = np.arange(1,26).reshape(5,5)
some_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [81]:
# NumPy slices
some_matrix[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [82]:
some_matrix[3,4]

20

In [83]:
some_matrix[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [84]:
some_matrix[:3,1]

array([ 2,  7, 12])

In [85]:
# Total sum
np.sum(some_matrix)

325

In [86]:
# Standard Deviation
some_matrix.std()

7.211102550927978

In [87]:
# Horizontal sum
some_matrix.sum(axis=0)

array([55, 60, 65, 70, 75])

In [88]:
# Vertical sum
some_matrix.sum(axis=1)

array([ 15,  40,  65,  90, 115])